### ISSUE TITLE
FORM is cached after updating from 3.1.2 to 3.2.0

### ISSUE THREAD

**Issue by aaronk6** [simonschaufi/ve_guestbook#1]
After upgrading from version 3.1.2 to version 3.2.0, the FORM component is cached. This breaks validation as well as the creation of new entries.

I saw you removed `$this->frontendController->set_no_cache();` in 1c4b5b9e245e532a47c97351c20af6c4095965c0. This could be the cause.

BTW, I’m using TYPO3 7.6.

**Comment by simonschaufi** [comment]
I noticed the same issue. The thing is, as far as I know, the removed line makes the whole page not cachable but I just want the form plugin to be not cached. Can you help me with a hint?

**Comment by aaronk6** [comment]
I’m no expert, but I tried to fix it based on this SO answer: http://stackoverflow.com/a/5405738/1387396

This includes registering the plugin as USER_INT by setting the last parameter of [addPItoST43](https://typo3.org/api/typo3cms/class_t_y_p_o3_1_1_c_m_s_1_1_core_1_1_utility_1_1_extension_management_utility.html#ac5855624506bf76452e495738be90132) to `1`. Note that I still set `$this->pi_USER_INT_obj` to `0` in the plugin class for codes other than FORM.

This fixes the issue but I’m not sure if this is the right approach. Thoughts?

**Comment by simonschaufi** [comment]
Thank you! as this is a really old extension, it just needs to work. A complete rewrite would be appropriate but since guestbooks are dying, i don't see the need.

**Comment by aaronk6** [comment]
I agree. Thanks for merging my PR.
