### ISSUE TITLE
commenting capability gone?

### ISSUE THREAD

**Issue by ntborg** [simonschaufi/ve_guestbook#3]
I'm currently working on a long needed upgrade of my blog, including tt_news and modernguestbook including 3000+ comments. After working hard on it I got from typo3 4.5 (yes I know) to Typo3 7.6.

But somewhere between some upgrades from tt_news to tx_news and the latest ve_guestbook I lost the relations between comments and news-items.

After some research I found out that a db table uid_tt_news has the relation-info to the specific blog . items, but is now renamed and not used by ve_guestbook. As far as I can see the old version had a link with this db entry in class.tx_veguestbook_pi1.php, but this is gone in the latest version.

Result is all 3000+ comments under every news-item.
A fresh install and setup of typo3, news and guestbook confirms it. It appears that the link to a comment to a specific news-item is non-existing in this new version of ve_guestbook.
And sinds googling for this problem did not help, I was hoping I could get some answers here :)

Can You throw some light on this matter? Thank You in advance. I have enjoyed this extension a lot, but was hoping that I still could after upgrade.

**Comment by simonschaufi** [comment]
Hello,
the commenting feature was dropped as it [caused lots of problems](https://github.com/simonschaufi/ve_guestbook/commit/1c4b5b9e245e532a47c97351c20af6c4095965c0). I was just making the extension ready for 7.6 but didn't expect at all that people nowadays still use it.

3000+ comments is a lot. I would have recommended you to use a "proper" commenting extension which works way better than this one but I can offer you that I can implement that feature again as a payed version. If you are willing to invest in that feature, please let me know.

**Comment by ntborg** [comment]
The fact the Extension Manual on typo3.org still stated Commenting is a part of the extension threw me off. I could not find the flaw until I dug into the code. But it makes sense.  Typo3 is changing rapidly, its hard to keep up. Especially if it comes out of your spare time.
But I bet a lot still use this extension. For its time it was way ahead in its simplicity and stability. I loved it a lot. I think Ill move to another extension for the comments. Its for a private blog for family and friends so I cannot afford invest for a payed version. But thank You for this nice extension and the time You (have) put into it!
Ill definitely keep using it as a guestbook 👍
